### ISSUE TITLE
Test cases failed 

### ISSUE THREAD

**Issue by youngqqcn** [orientwalt/tendermint#1]
commit: aa235ace06b90c8701abc0e5a33474eebebfbfde

`make test`

failed at files  `consensus/replay_test.go` and  `evidence/reactor_test.go`

---

```
tendermint$ make test
--> Running go test
ok      github.com/tendermint/tendermint/abci/client    (cached)
?       github.com/tendermint/tendermint/abci/cmd/abci-cli      [no test files]
ok      github.com/tendermint/tendermint/abci/example   (cached)
?       github.com/tendermint/tendermint/abci/example/code      [no test files]
?       github.com/tendermint/tendermint/abci/example/counter   [no test files]
ok      github.com/tendermint/tendermint/abci/example/kvstore   (cached)
?       github.com/tendermint/tendermint/abci/server    [no test files]
ok      github.com/tendermint/tendermint/abci/tests     (cached)
?       github.com/tendermint/tendermint/abci/tests/benchmarks  [no test files]
?       github.com/tendermint/tendermint/abci/tests/benchmarks/parallel [no test files]
?       github.com/tendermint/tendermint/abci/tests/benchmarks/simple   [no test files]
?       github.com/tendermint/tendermint/abci/tests/server      [no test files]
?       github.com/tendermint/tendermint/abci/tests/test_app    [no test files]
ok      github.com/tendermint/tendermint/abci/types     (cached)
?       github.com/tendermint/tendermint/abci/version   [no test files]
ok      github.com/tendermint/tendermint/behaviour      (cached)
ok      github.com/tendermint/tendermint/blockchain/v0  4.425s
ok      github.com/tendermint/tendermint/blockchain/v1  7.689s
ok      github.com/tendermint/tendermint/blockchain/v2  0.048s
?       github.com/tendermint/tendermint/cmd/contract_tests     [no test files]
?       github.com/tendermint/tendermint/cmd/priv_val_server    [no test files]
?       github.com/tendermint/tendermint/cmd/tendermint [no test files]
ok      github.com/tendermint/tendermint/cmd/tendermint/commands        0.035s
?       github.com/tendermint/tendermint/cmd/tendermint/commands/debug  [no test files]
ok      github.com/tendermint/tendermint/config (cached)
--- FAIL: TestHandshakeReplayAll (0.09s)
    replay_test.go:662: 
                Error Trace:    replay_test.go:662
                                                        replay_test.go:525
                Error:          Received unexpected error:
                                wal does not contain height 0
                Test:           TestHandshakeReplayAll
--- FAIL: TestHandshakeReplaySome (0.09s)
    replay_test.go:662: 
                Error Trace:    replay_test.go:662
                                                        replay_test.go:535
                Error:          Received unexpected error:
                                wal does not contain height 0
                Test:           TestHandshakeReplaySome
--- FAIL: TestHandshakeReplayOne (0.09s)
    replay_test.go:662: 
                Error Trace:    replay_test.go:662
                                                        replay_test.go:545
                Error:          Received unexpected error:
                                wal does not contain height 0
                Test:           TestHandshakeReplayOne
--- FAIL: TestHandshakeReplayNone (0.09s)
    replay_test.go:662: 
                Error Trace:    replay_test.go:662
                                                        replay_test.go:555
                Error:          Received unexpected error:
                                wal does not contain height 0
                Test:           TestHandshakeReplayNone
--- FAIL: TestSetValidBlockOnDelayedPrevote (0.12s)
panic: Timeout expired while waiting for NewValidBlock event [recovered]
        panic: Timeout expired while waiting for NewValidBlock event

goroutine 39929 [running]:
testing.tRunner.func1.2(0xba8180, 0xc00197c060)
        /usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc00100ed80)
        /usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0xba8180, 0xc00197c060)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/tendermint/tendermint/consensus.ensureNewEvent(0xc00aa8a4e0, 0x1, 0x0, 0x5f5e100, 0xcde41f, 0x35)
        /data2/work/tendermint/consensus/common_test.go:463 +0x170
github.com/tendermint/tendermint/consensus.ensureNewValidBlock(...)
        /data2/work/tendermint/consensus/common_test.go:525
github.com/tendermint/tendermint/consensus.TestSetValidBlockOnDelayedPrevote(0xc00100ed80)
        /data2/work/tendermint/consensus/state_test.go:1054 +0x79c
testing.tRunner(0xc00100ed80, 0xe18468)
        /usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1238 +0x2b3
FAIL    github.com/tendermint/tendermint/consensus      7.481s
ok      github.com/tendermint/tendermint/consensus/types        (cached)
ok      github.com/tendermint/tendermint/crypto (cached)
ok      github.com/tendermint/tendermint/crypto/armor   (cached)
ok      github.com/tendermint/tendermint/crypto/ed25519 (cached)
ok      github.com/tendermint/tendermint/crypto/encoding/amino  (cached)
?       github.com/tendermint/tendermint/crypto/internal/benchmarking   [no test files]
ok      github.com/tendermint/tendermint/crypto/merkle  (cached)
ok      github.com/tendermint/tendermint/crypto/multisig        (cached)
ok      github.com/tendermint/tendermint/crypto/multisig/bitarray       (cached)
ok      github.com/tendermint/tendermint/crypto/secp256k1       (cached)
?       github.com/tendermint/tendermint/crypto/secp256k1/internal/secp256k1    [no test files]
ok      github.com/tendermint/tendermint/crypto/sr25519 (cached)
ok      github.com/tendermint/tendermint/crypto/tmhash  (cached)
ok      github.com/tendermint/tendermint/crypto/xchacha20poly1305       (cached)
ok      github.com/tendermint/tendermint/crypto/xsalsa20symmetric       (cached)
--- FAIL: TestReactorBroadcastEvidence (120.02s)
    reactor_test.go:112: 
                Error Trace:    reactor_test.go:112
                                                        reactor_test.go:149
                Error:          Expected nil, but got: evidence.ErrInvalidEvidence{Reason:state.ErrNoValSetForHeight{Height:2}}
                Test:           TestReactorBroadcastEvidence
    reactor_test.go:73: Timed out waiting for evidence
--- FAIL: TestReactorSelectiveBroadcast (120.00s)
    reactor_test.go:112: 
                Error Trace:    reactor_test.go:112
                                                        reactor_test.go:189
                Error:          Expected nil, but got: evidence.ErrInvalidEvidence{Reason:state.ErrNoValSetForHeight{Height:2}}
                Test:           TestReactorSelectiveBroadcast
    reactor_test.go:73: Timed out waiting for evidence
FAIL
FAIL    github.com/tendermint/tendermint/evidence       242.094s
?       github.com/tendermint/tendermint/github.com/tendermint/tendermint/abci/types    [no test files]
ok      github.com/tendermint/tendermint/libs/async     (cached)
ok      github.com/tendermint/tendermint/libs/autofile  (cached)
?       github.com/tendermint/tendermint/libs/autofile/cmd      [no test files]
ok      github.com/tendermint/tendermint/libs/bech32    (cached)
ok      github.com/tendermint/tendermint/libs/bits      (cached)
ok      github.com/tendermint/tendermint/libs/bytes     (cached)
ok      github.com/tendermint/tendermint/libs/cli       (cached)
ok      github.com/tendermint/tendermint/libs/cli/flags (cached)
ok      github.com/tendermint/tendermint/libs/clist     (cached)
ok      github.com/tendermint/tendermint/libs/cmap      (cached)
ok      github.com/tendermint/tendermint/libs/events    (cached)
?       github.com/tendermint/tendermint/libs/fail      [no test files]
ok      github.com/tendermint/tendermint/libs/flowrate  (cached)
ok      github.com/tendermint/tendermint/libs/kv        (cached)
ok      github.com/tendermint/tendermint/libs/log       (cached)
?       github.com/tendermint/tendermint/libs/math      [no test files]
ok      github.com/tendermint/tendermint/libs/net       (cached)
?       github.com/tendermint/tendermint/libs/os        [no test files]
ok      github.com/tendermint/tendermint/libs/pubsub    (cached)
ok      github.com/tendermint/tendermint/libs/pubsub/query      (cached)
?       github.com/tendermint/tendermint/libs/pubsub/query/fuzz_test    [no test files]
ok      github.com/tendermint/tendermint/libs/rand      (cached)
ok      github.com/tendermint/tendermint/libs/service   (cached)
ok      github.com/tendermint/tendermint/libs/strings   (cached)
ok      github.com/tendermint/tendermint/libs/tempfile  (cached)
?       github.com/tendermint/tendermint/libs/test      [no test files]
ok      github.com/tendermint/tendermint/libs/timer     (cached)
ok      github.com/tendermint/tendermint/lite   (cached)
ok      github.com/tendermint/tendermint/lite/client    5.550s
?       github.com/tendermint/tendermint/lite/errors    [no test files]
ok      github.com/tendermint/tendermint/lite/proxy     0.578s
ok      github.com/tendermint/tendermint/lite2  21.322s
?       github.com/tendermint/tendermint/lite2/provider [no test files]
ok      github.com/tendermint/tendermint/lite2/provider/http    5.551s
?       github.com/tendermint/tendermint/lite2/provider/mock    [no test files]
?       github.com/tendermint/tendermint/lite2/proxy    [no test files]
ok      github.com/tendermint/tendermint/lite2/rpc      (cached) [no tests to run]
?       github.com/tendermint/tendermint/lite2/store    [no test files]
ok      github.com/tendermint/tendermint/lite2/store/db (cached)
ok      github.com/tendermint/tendermint/mempool        (cached)
?       github.com/tendermint/tendermint/mock   [no test files]
ok      github.com/tendermint/tendermint/node   6.062s
ok      github.com/tendermint/tendermint/p2p    (cached)
ok      github.com/tendermint/tendermint/p2p/conn       (cached)
?       github.com/tendermint/tendermint/p2p/mock       [no test files]
ok      github.com/tendermint/tendermint/p2p/pex        (cached)
ok      github.com/tendermint/tendermint/p2p/trust      (cached)
?       github.com/tendermint/tendermint/p2p/upnp       [no test files]
ok      github.com/tendermint/tendermint/privval        (cached)
ok      github.com/tendermint/tendermint/proxy  (cached)
ok      github.com/tendermint/tendermint/rpc/client     9.450s
?       github.com/tendermint/tendermint/rpc/client/http        [no test files]
?       github.com/tendermint/tendermint/rpc/client/local       [no test files]
ok      github.com/tendermint/tendermint/rpc/client/mock        0.025s
ok      github.com/tendermint/tendermint/rpc/core       0.028s
ok      github.com/tendermint/tendermint/rpc/core/types (cached)
ok      github.com/tendermint/tendermint/rpc/grpc       0.059s
ok      github.com/tendermint/tendermint/rpc/lib        (cached)
ok      github.com/tendermint/tendermint/rpc/lib/client (cached)
ok      github.com/tendermint/tendermint/rpc/lib/server (cached)
?       github.com/tendermint/tendermint/rpc/lib/test   [no test files]
ok      github.com/tendermint/tendermint/rpc/lib/types  (cached)
?       github.com/tendermint/tendermint/rpc/test       [no test files]
ok      github.com/tendermint/tendermint/scripts        (cached)
?       github.com/tendermint/tendermint/scripts/json2wal       [no test files]
?       github.com/tendermint/tendermint/scripts/wal2json       [no test files]
ok      github.com/tendermint/tendermint/state  2.976s
ok      github.com/tendermint/tendermint/state/txindex  (cached)
ok      github.com/tendermint/tendermint/state/txindex/kv       (cached)
?       github.com/tendermint/tendermint/state/txindex/null     [no test files]
ok      github.com/tendermint/tendermint/store  1.374s
?       github.com/tendermint/tendermint/test/app       [no test files]
?       github.com/tendermint/tendermint/tools/tm-signer-harness        [no test files]
ok      github.com/tendermint/tendermint/tools/tm-signer-harness/internal       0.053s
ok      github.com/tendermint/tendermint/types  3.713s
?       github.com/tendermint/tendermint/types/proto3   [no test files]
ok      github.com/tendermint/tendermint/types/time     (cached)
?       github.com/tendermint/tendermint/version        [no test files]
FAIL
make: *** [tests.mk:106：test] 错误 1
yqq@ubuntu:tendermint$ 
```

**Comment by deep2chain** [comment]
The official repo didn't resolve it, too. I am investigating now. It will take some days.
```
$ cd github.com/tendermint/tendermint
$ git branch
* (HEAD detached at v0.34.0-rc3)
  master
$ make test
--> Running go test
ok      github.com/tendermint/tendermint/abci/client    (cached)
?       github.com/tendermint/tendermint/abci/client/mocks   [no test files]
?       github.com/tendermint/tendermint/abci/cmd/abci-cli   [no test files]
ok      github.com/tendermint/tendermint/abci/example   (cached)
?       github.com/tendermint/tendermint/abci/example/code   [no test files]
?       github.com/tendermint/tendermint/abci/example/counter[no test files]
ok      github.com/tendermint/tendermint/abci/example/kvstore(cached)
?       github.com/tendermint/tendermint/abci/server    [no test files]
ok      github.com/tendermint/tendermint/abci/tests     (cached)
?       github.com/tendermint/tendermint/abci/tests/benchmarks[no test files]
?       github.com/tendermint/tendermint/abci/tests/benchmarks/parallel       [no test files]
?       github.com/tendermint/tendermint/abci/tests/benchmarks/simple [no test files]
?       github.com/tendermint/tendermint/abci/tests/server   [no test files]
?       github.com/tendermint/tendermint/abci/tests/test_app [no test files]
ok      github.com/tendermint/tendermint/abci/types     (cached)
?       github.com/tendermint/tendermint/abci/version   [no test files]
ok      github.com/tendermint/tendermint/behaviour      (cached)
ok      github.com/tendermint/tendermint/blockchain     (cached)
ok      github.com/tendermint/tendermint/blockchain/v0  (cached)
ok      github.com/tendermint/tendermint/blockchain/v1  (cached)
ok      github.com/tendermint/tendermint/blockchain/v2  (cached)
?       github.com/tendermint/tendermint/cmd/contract_tests     [no test files]
?       github.com/tendermint/tendermint/cmd/priv_val_server    [no test files]
# github.com/tendermint/tendermint/p2p/upnp
p2p/upnp/upnp.go:212:20: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
?       github.com/tendermint/tendermint/cmd/tendermint [no test files]
ok      github.com/tendermint/tendermint/cmd/tendermint/commands      (cached)
?       github.com/tendermint/tendermint/cmd/tendermint/commands/debug        [no test files]
ok      github.com/tendermint/tendermint/config (cached)
--- FAIL: TestByzantinePrevoteEquivocation (0.53s)
    byzantine_test.go:173: 
                Error Trace:    byzantine_test.go:173
                Error:          Expected value not to be nil.
                Test:           TestByzantinePrevoteEquivocation
FAIL
FAIL    github.com/tendermint/tendermint/consensus      24.980s
ok      github.com/tendermint/tendermint/consensus/types     (cached)
ok      github.com/tendermint/tendermint/crypto (cached)
ok      github.com/tendermint/tendermint/crypto/armor   (cached)
ok      github.com/tendermint/tendermint/crypto/ed25519 (cached)
?       github.com/tendermint/tendermint/crypto/encoding     [no test files]
?       github.com/tendermint/tendermint/crypto/internal/benchmarking [no test files]
ok      github.com/tendermint/tendermint/crypto/merkle  (cached)
ok      github.com/tendermint/tendermint/crypto/secp256k1    (cached)
?       github.com/tendermint/tendermint/crypto/secp256k1/internal/secp256k1  [no test files]
ok      github.com/tendermint/tendermint/crypto/sr25519 (cached)
ok      github.com/tendermint/tendermint/crypto/tmhash  (cached)
ok      github.com/tendermint/tendermint/crypto/xchacha20poly1305     (cached)
ok      github.com/tendermint/tendermint/crypto/xsalsa20symmetric     (cached)
ok      github.com/tendermint/tendermint/evidence       (cached)
?       github.com/tendermint/tendermint/evidence/mocks [no test files]
ok      github.com/tendermint/tendermint/libs/async     (cached)
--- FAIL: TestWrite (0.07s)
    group_test.go:35: 
                Error Trace:    group_test.go:35
                                                        group_test.go:194
                Error:          Received unexpected error:
                                unlinkat /media/gustav/Investigation/github.com/tendermint/tendermint/libs/autofile/_test_kpgivO8LZgxU: directory not empty
                Test:           TestWrite
                Messages:       Error removing test Group directory
--- FAIL: TestGroupReaderRead (0.12s)
    group_test.go:35: 
                Error Trace:    group_test.go:35
                                                        group_test.go:227
                Error:          Received unexpected error:
                                unlinkat /media/gustav/Investigation/github.com/tendermint/tendermint/libs/autofile/_test_8pctULF8uGSe: directory not empty
                Test:           TestGroupReaderRead
                Messages:       Error removing test Group directory
--- FAIL: TestGroupReaderRead2 (0.12s)
    group_test.go:35: 
                Error Trace:    group_test.go:35
                                                        group_test.go:264
                Error:          Received unexpected error:
                                unlinkat /media/gustav/Investigation/github.com/tendermint/tendermint/libs/autofile/_test_KvV38WmyqAhr: directory not empty
                Test:           TestGroupReaderRead2
                Messages:       Error removing test Group directory
FAIL
FAIL    github.com/tendermint/tendermint/libs/autofile  2.640s
?       github.com/tendermint/tendermint/libs/autofile/cmd   [no test files]
ok      github.com/tendermint/tendermint/libs/bits      (cached)
ok      github.com/tendermint/tendermint/libs/bytes     (cached)
ok      github.com/tendermint/tendermint/libs/cli       (cached)
ok      github.com/tendermint/tendermint/libs/cli/flags (cached)
ok      github.com/tendermint/tendermint/libs/clist     (cached)
# github.com/tendermint/tendermint/libs/cmap
libs/cmap/cmap_test.go:63:9: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
libs/cmap/cmap_test.go:67:9: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    github.com/tendermint/tendermint/libs/cmap [build failed]
ok      github.com/tendermint/tendermint/libs/events    (cached)
?       github.com/tendermint/tendermint/libs/fail      [no test files]
ok      github.com/tendermint/tendermint/libs/flowrate  (cached)
ok      github.com/tendermint/tendermint/libs/json      (cached)
ok      github.com/tendermint/tendermint/libs/log       (cached)
ok      github.com/tendermint/tendermint/libs/math      (cached)
ok      github.com/tendermint/tendermint/libs/net       (cached)
ok      github.com/tendermint/tendermint/libs/os        (cached)
ok      github.com/tendermint/tendermint/libs/protoio   (cached)
# github.com/tendermint/tendermint/libs/pubsub_test
libs/pubsub/pubsub_test.go:447:81: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    github.com/tendermint/tendermint/libs/pubsub [build failed]
ok      github.com/tendermint/tendermint/libs/pubsub/query   (cached)
?       github.com/tendermint/tendermint/libs/pubsub/query/fuzz_test  [no test files]
ok      github.com/tendermint/tendermint/libs/rand      (cached)
ok      github.com/tendermint/tendermint/libs/service   (cached)
ok      github.com/tendermint/tendermint/libs/strings   (cached)
?       github.com/tendermint/tendermint/libs/sync      [no test files]
ok      github.com/tendermint/tendermint/libs/tempfile  (cached)
?       github.com/tendermint/tendermint/libs/test      [no test files]
ok      github.com/tendermint/tendermint/libs/timer     (cached)
ok      github.com/tendermint/tendermint/light  (cached)
?       github.com/tendermint/tendermint/light/provider [no test files]
ok      github.com/tendermint/tendermint/light/provider/http (cached)
?       github.com/tendermint/tendermint/light/provider/mock [no test files]
?       github.com/tendermint/tendermint/light/proxy    [no test files]
ok      github.com/tendermint/tendermint/light/rpc      (cached) [no tests to run]
?       github.com/tendermint/tendermint/light/store    [no test files]
ok      github.com/tendermint/tendermint/light/store/db (cached)
ok      github.com/tendermint/tendermint/mempool        (cached)
?       github.com/tendermint/tendermint/mempool/mock   [no test files]
ok      github.com/tendermint/tendermint/node   (cached)
ok      github.com/tendermint/tendermint/p2p    (cached)
ok      github.com/tendermint/tendermint/p2p/conn       (cached)
?       github.com/tendermint/tendermint/p2p/mock       [no test files]
?       github.com/tendermint/tendermint/p2p/mocks      [no test files]
ok      github.com/tendermint/tendermint/p2p/pex        (cached)
ok      github.com/tendermint/tendermint/p2p/trust      (cached)
ok      github.com/tendermint/tendermint/privval        (cached)
ok      github.com/tendermint/tendermint/proxy  (cached)
ok      github.com/tendermint/tendermint/rpc/client     (cached)
ok      github.com/tendermint/tendermint/rpc/client/mock     (cached)
ok      github.com/tendermint/tendermint/rpc/core       (cached)
ok      github.com/tendermint/tendermint/rpc/core/types (cached)
ok      github.com/tendermint/tendermint/rpc/grpc       (cached)
ok      github.com/tendermint/tendermint/rpc/jsonrpc    (cached)
ok      github.com/tendermint/tendermint/rpc/jsonrpc/client  (cached)
ok      github.com/tendermint/tendermint/rpc/jsonrpc/server  (cached)
ok      github.com/tendermint/tendermint/rpc/jsonrpc/types   (cached)
ok      github.com/tendermint/tendermint/state  (cached)
ok      github.com/tendermint/tendermint/state/txindex  (cached)
ok      github.com/tendermint/tendermint/state/txindex/kv    (cached)
ok      github.com/tendermint/tendermint/statesync      (cached)
ok      github.com/tendermint/tendermint/store  (cached)
ok      github.com/tendermint/tendermint/tools/tm-signer-harness/internal     (cached)
ok      github.com/tendermint/tendermint/types  (cached)
ok      github.com/tendermint/tendermint/types/time     (cached)
tests.mk:105: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by youngqqcn** [comment]
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^(TestMain|TestWALCrash|TestSimulateValidatorsChange|TestHandshakeReplayAll|TestHandshakeReplaySome|TestHandshakeReplayOne|TestHandshakeReplayNone|TestMockProxyApp|TestHandshakePanicsIfAppReturnsWrongAppHash|TestHandshakeUpdatesValidators)$ github.com/tendermint/tendermint/consensus

--- FAIL: TestHandshakeReplayAll (0.25s)
panic: wrong Block.Header.LastBlockID.  Expected BE22E30EB02F32FFDB7C373F73284C1456C483BCB6B3382F3EC81826037F746B:1:A26FEAF7EEC6, got BE22E30EB02F32FFDB7C373F73284C1456C483BCB6B3382F3EC81826037F746B:1:A5F91AD6D0D8 [recovered]
	panic: wrong Block.Header.LastBlockID.  Expected BE22E30EB02F32FFDB7C373F73284C1456C483BCB6B3382F3EC81826037F746B:1:A26FEAF7EEC6, got BE22E30EB02F32FFDB7C373F73284C1456C483BCB6B3382F3EC81826037F746B:1:A5F91AD6D0D8

goroutine 1993 [running]:
testing.tRunner.func1.2(0xbc9d60, 0xc000dd4380)
	/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000582a80)
	/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0xbc9d60, 0xc000dd4380)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/tendermint/tendermint/consensus.applyBlock(0xee3ac0, 0xc00197f2a0, 0xa, 0x1, 0xcb66e6, 0x6, 0xcbe5da, 0xf, 0x1, 0x1, ...)
	/data2/work/tendermint/consensus/replay_test.go:748 +0x397
github.com/tendermint/tendermint/consensus.buildTMStateFromChain(0xc0001c92c0, 0xee3ac0, 0xc00197f2a0, 0xa, 0x1, 0xcb66e6, 0x6, 0xcbe5da, 0xf, 0x1, ...)
	/data2/work/tendermint/consensus/replay_test.go:830 +0x7df
github.com/tendermint/tendermint/consensus.testHandshakeReplay(0xc000582a80, 0xc0001c92c0, 0x0, 0x1, 0xc000f27701)
	/data2/work/tendermint/consensus/replay_test.go:673 +0x628
github.com/tendermint/tendermint/consensus.TestHandshakeReplayAll(0xc000582a80)
	/data2/work/tendermint/consensus/replay_test.go:529 +0xdd
testing.tRunner(0xc000582a80, 0xe187b0)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
FAIL	github.com/tendermint/tendermint/consensus	1.935s
FAIL
```

reactor

```go

	switch chID {
	case StateChannel:
		switch msg := msg.(type) {
		case *NewRoundStepMessage:
			// conR.conS.mtx.Lock()
			// initialHeight := conR.conS.state.InitialHeight
			// conR.conS.mtx.Unlock()
			// if err = msg.ValidateHeight(initialHeight); err != nil {
			// 	conR.Logger.Error("Peer sent us invalid msg", "peer", src, "msg", msg, "err", err)
			// 	conR.Switch.StopPeerForError(src, err)
			// 	return
			// }
			ps.ApplyNewRoundStepMessage(msg)
		case *NewValidBlockMessage:
			ps.ApplyNewValidBlockMessage(msg)
		case *HasVoteMessage:
			ps.ApplyHasVoteMessage(msg)
```

**Comment by youngqqcn** [comment]
```
--- FAIL: TestReactorBroadcastEvidence (120.02s)
    reactor_test.go:112: 
                Error Trace:    reactor_test.go:112
                                                        reactor_test.go:149
                Error:          Expected nil, but got: evidence.ErrInvalidEvidence{Reason:state.ErrNoValSetForHeight{Height:2}}
                Test:           TestReactorBroadcastEvidence
    reactor_test.go:73: Timed out waiting for evidence
--- FAIL: TestReactorSelectiveBroadcast (120.01s)
    reactor_test.go:112: 
                Error Trace:    reactor_test.go:112
                                                        reactor_test.go:189
                Error:          Expected nil, but got: evidence.ErrInvalidEvidence{Reason:state.ErrNoValSetForHeight{Height:2}}
                Test:           TestReactorSelectiveBroadcast
    reactor_test.go:73: Timed out waiting for evidence
FAIL
FAIL    github.com/tendermint/tendermint/evidence       242.149s
```
